# ANX HTTP Server Configuration
# This is an example configuration file in TOML format

[server]
listen = ["80", "443"]
server_name = "example.com"
root = "/var/www/html"
index = ["index.html", "index.htm"]
worker_processes = 4
worker_connections = 1024
keepalive_timeout = 65
client_max_body_size = "10M"

[logging]
access_log = "/var/log/anx/access.log"
error_log = "/var/log/anx/error.log"
log_level = "info"

[ssl]
certificate = "/etc/ssl/certs/example.com.crt"
private_key = "/etc/ssl/private/example.com.key"
protocols = ["TLSv1.2", "TLSv1.3"]
ciphers = "ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384"

[proxy]
proxy_timeout = 60
proxy_connect_timeout = 5

[proxy.upstream]
backend = ["127.0.0.1:8001", "127.0.0.1:8002"]
api = ["127.0.0.1:9001"]

[cache]
enabled = true
max_size = "100M"
ttl = 3600
keys_zone = "main:10m"

[[locations]]
path = "/"
root = "/var/www/html"
index = ["index.html"]

[[locations]]
path = "/api"
proxy_pass = "http://backend"

[[locations]]
path = "/static"
root = "/var/www/static"
try_files = ["$uri", "$uri/", "@fallback"]

[locations.headers]
"X-Frame-Options" = "SAMEORIGIN"
"X-Content-Type-Options" = "nosniff" 